### ISSUE TITLE
Xpath option together with CSS or vice versa

### ISSUE THREAD

**Issue by Noman-tufail** [further-reading/scraping-browser#23]
Hi
While reading scrapy documetation ("Selector" segment) it is recommended to first select the class by css then apply either Xpath or regex. we have regex in GUI but not xpath.

to further explain I mean selector equivalent to this ----> selector.css(css_query).xpath(xpath_query)

**Comment by further-reading** [comment]
I think you're misreading the documentation - you can choose to either use css or xpath when making a query:`sel.css(query)` or `sel.xpath(query)`.  The output of both are themselves selectors so you can chain the same way `sel.css(query).css(query).xpath(query).css(query)` and so on ad infinitum. I don't believe there's specific advice to use css and then xpath -  you can use either in any order and any amount (in fact the best practice is to not mix at all but to choose one query language for a project). 

In my experience I can't recall a single instance where I'd need to chain selectors like this. More typically I'd have something like `products = response.css('div.product')`to grab a collection of products for example, then iterate over to extract each product separately. When using scrapy_gui in this case I'd be using load_selector with one of elements of products rather than doing both steps at once via the UI. 

If you want to test a complex selector chain like there are two options:

Option 1. `load_selector` function on the output of the first query in the chain:     
```python
# for response.css(css_query).xpath(xpath_query)
css_sel = response.css(css_query)
load_selector(css_sel) 
```

Option 2. Use any placeholder in the query box box then use the function box to write the more complex multistep selector. 

```python 

def user_fun(results, selector):
    # ignore results, make the two step selector
    sel = selector. css(css_query).xpath(xpath_query)
    return sel.get_all()   # or sel.re(regex)
```

I'd consider this an edge case that's out of scope of a dedicated UI for it and the two workarounds should suffice for this scenario.

**Comment by Noman-tufail** [comment]
I am very thankful to you for your comprehensive reply.

Scrapy documentation is an exception in the world of python in the sense
that it is written exceptionally well. This fact is also admitted in web
scraping books I read.

So I read this documentation two three times.

Here is reference which I made

Documentation : Version :2.6
Section : Selectors
Heading : When querying by class, consider using CSS.

Reference is as follows : I QUOTE

" As it turns out, Scrapy selectors allow you to chain selectors, so most
of the time you can just select by class using CSS and then switch to XPath
when needed"

Then following example is mentioned.

from scrapy import Selector

sel = Selector(text='<div class="hero shout"><time datetime="2014-07-23
19:00">Special date</time></div>')


***@***.***').getall()

Output :
['2014-07-23 19:00']



I understand your advice and options given. I will consider using option 2
when required.

And thankful for this GUI for scrapy shell. As it has made using scrapy
more easy and fun.

Regards,
Noman Tufail
ACA, PIPFA, MCOM
